### ISSUE TITLE
Is this a fork of AntennaPod?

### ISSUE THREAD

**Issue by Coehill** [allentown521/FocusPodcast#10]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/allentown521/FocusPodcast/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/allentown521/FocusPodcast/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain podcast, I will include the URL of that podcast.

### App version

N/A

### Where did you get the app from

Google Play

### Android version

N/A

### Expected behaviour

I'm asking because it looks very similar and uses the antenna pod media player. However I don't see attribution.

https://github.com/allentown521/FocusPodcast/blob/821c7c851e260d0acdf623c5e59a2c0f63544c80/core/build.gradle#L74

**Comment by allentown521** [comment]
yes
