### ISSUE TITLE
Widgets are not working correctly, they are flickering

### ISSUE THREAD

**Issue by Slawa79** [allentown521/FocusPodcast#5]
When playing podcasts, if there is a widget on the screen, it flashes, flickers. I'm not doing anything special, I just installed a widget from this application on the screen, but it flickers. 
 [ realme C25 smartphone; android 13 ; no root rights ]

https://github.com/allentown521/FocusPodcast/assets/23304238/af9a9a2f-0f58-4503-bdec-625e4b664837

![log.txt](https://github.com/user-attachments/files/16109099/log.txt)

**Comment by allentown521** [comment]
This looks weird, I have everything working fine here, I will check if the android 13 emulator has that issue

**Comment by allentown521** [comment]
> Record_2024-07-11-21-03-34.mp4 
> Hi. I reinstalled the app today and now the widgets are working fine. Apparently, the problem has been solved, it's a pity that I didn't reinstall the application earlier, but only disturbed you. Sorry.

It doesn't matter, so just reinstall without uninstalling first? This also makes me unable to understand lol
