### ISSUE TITLE
com.google.android.wearable is not FOSS

### ISSUE THREAD

**Issue by licaon-kter** [allentown521/FocusPodcast#7]
ref: https://github.com/allentown521/FocusPodcast/blob/2.8.0.20240624/app/build.gradle#L181

ref: https://github.com/allentown521/FocusPodcast/blob/2.8.0.20240624/core/build.gradle#L79

from that lib you only pull `com/google/android/wearable/compat/WearableActivityController` why?

fyi that's part of `androidx.wear:wear` so maybe you can replace those with this one?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/issues/3306#note_1992987829

**Comment by allentown521** [comment]
https://github.com/allentown521/FocusPodcast/commit/5e2060b1265a427167d4f91a980d59edee68efed

removed now
